### ISSUE TITLE
Syntax not activated automatically

### ISSUE THREAD

**Issue by smutel** [gutenye/json5.vim#2]
Hello,

I don't know why but on my pc, the json5 syntax is not set automatically.
I need to enter manually:
`:set syntax=json5`

Do you have an idea how to troubleshoot this ?

Thanks.

**Comment by gutenye** [comment]
It's auto detected by https://github.com/gutenye/json5.vim/blob/master/ftdetect/json5.vim#L1

If not work, you can add that into your ~/.vim/ftdetect.vim file (if I remember the path correctly)

**Comment by smutel** [comment]
The issue seems to be in vim itself. The version 8.0.1453 is installed by default with my distrib. I installed a newer version (8.1.527) and it is working fine with the same config. Thanks.
