### ISSUE TITLE
Detect json5 for `.json` if file has comments

### ISSUE THREAD

**Issue by gnidan** [gutenye/json5.vim#7]
I believe Vim has the capability of recognizing filetype based on the contents of the file, not just the extension.

It'd be nice if this plugin could detect `.json` files that have comments and set the filetype as `json5` accordingly.

Thanks for your consideration!

**Comment by IzhakJakov** [comment]
Try adding the `// vi: set ft=json5` as the first line in your `.json` file

**Comment by gutenye** [comment]
@izhakjakov Thanks for the solution

**Comment by IzhakJakov** [comment]
🙂 yw
