### ISSUE TITLE
Merge upstream?

### ISSUE THREAD

**Issue by mazunki** [gutenye/json5.vim#8]
Hello,

I'm reaching out because of a recent discussion over at Vim's repository regarding native support for json5/jsonc. A lot of projects are starting to use json5 for config files, and it'd be convenient if Vim supported it out of the box.

Would you be open to the idea of merging this project into Vim's upstream? This way, users wouldn't need to install a separate plugin for json5 support.

For reference: https://github.com/vim/vim/issues/8499

Thank you :)

**Comment by gutenye** [comment]
Yes, I would love to do that. How to proceed?

**Comment by mazunki** [comment]
Making a pull request to the vim repository linking to the aforementioned issue, and copying the files from here to `runtime/` over there, I believe.

If you want to I can open the pull request, and include you as the author.

**Comment by gutenye** [comment]
@mazunki Yes, please do it for me, thanks.

**Comment by mazunki** [comment]
@gutenye Thanks, it's now merged into both vim and neovim :)

Should we update the README here to mention it?

**Comment by gutenye** [comment]
@mazunki Thank you very much, yes please, I can also archive this repo.
